CREATE TABLE IF NOT EXISTS USERTABLE (userid VARCHAR(50) NOT NULL PRIMARY KEY,password VARCHAR(50),firstName VARCHAR(50),lastName VARCHAR(50),token VARCHAR(100),id INTEGER);

insert into USERTABLE(userid, password, firstName, lastName, token, id) values ('maxime', 'pass1234', 'Maxime', 'Muster', 'N0FlE_wwjoCG2mfqLPYq0NP8TIco8vb-','2');
insert into USERTABLE(userid, password, firstName, lastName, token, id) values ('jane', 'pass1234', 'Jane', 'Doe', 'yAY-txa3783OSn1Gyjm9Nk69zPkZz55h', '1');

CREATE TABLE IF NOT EXISTS SONG (id INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,title VARCHAR(50) NOT NULL,artist VARCHAR(50) NOT NULL,label VARCHAR(50),released VARCHAR(50),album VARCHAR(50));
insert into SONG(title, artist, label, released, album) values ('MacArthur Park', 'Richard Harris', 'Dunhill Records', '1968', 'Live and More');
insert into SONG(title, artist, label, released, album) values ('Afternoon Delight', 'Starland Vocal Band', 'Windsong', '1976', 'Starland Vocal Band');
insert into SONG(title, artist, label, released, album) values ('Muskrat Love', 'Captain and Tennille', 'A&M', '1976', 'Song of Joy');

CREATE TABLE IF NOT EXISTS SONGLIST (id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,isprivate BOOLEAN DEFAULT FALSE NOT NULL,ownerid VARCHAR(50) NOT NULL,name VARCHAR(50),FOREIGN KEY (ownerid) REFERENCES USERTABLE(userid));
insert into SONGLIST(isprivate, ownerid, name) values (false, 'maxime', 'MaxPrivate');
insert into SONGLIST(isprivate, ownerid, name) values (true, 'maxime', 'MaxPublic');
insert into SONGLIST(isprivate, ownerid, name) values (true, 'jane', 'JanesPrivate');
insert into SONGLIST(isprivate, ownerid, name) values (false, 'jane', 'JanesPublic');

CREATE TABLE IF NOT EXISTS SONGLIST_SONG (songlist_id INTEGER,song_id INTEGER, FOREIGN KEY (songlist_id) REFERENCES SONGLIST (id),  FOREIGN KEY (song_id) REFERENCES SONG (id));
insert into SONGLIST_SONG(songlist_id, song_id) values ('1', '2');
insert into SONGLIST_SONG(songlist_id, song_id) values ('1', '1');
insert into SONGLIST_SONG(songlist_id, song_id) values ('2', '2');
insert into SONGLIST_SONG(songlist_id, song_id) values ('2', '3');
insert into SONGLIST_SONG(songlist_id, song_id) values ('3', '1');
insert into SONGLIST_SONG(songlist_id, song_id) values ('3', '2');
insert into SONGLIST_SONG(songlist_id, song_id) values ('4', '1');
insert into SONGLIST_SONG(songlist_id, song_id) values ('4', '3');